config/routes.rb
Rails.application.routes.draw do
  resources :capybaras
  resources :dogs
  resources :cats
  resources :animals
  resources :transbanks
  resources :payment_methods
  resources :stripes
  resources :paypals
  resources :oneclicks
  resources :webpays
  resources :creditcards
  resources :orders
  resources :physicals
  resources :digitals
  resources :products
  resources :profiles
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/animal.rb
class Animal < ApplicationRecord
  belongs_to :specie
end

app/models/capybara.rb
class Capybara < ApplicationRecord
end

app/models/cat.rb
class Cat < ApplicationRecord
end

app/models/creditcard.rb
class Creditcard < ApplicationRecord
end

app/models/digital.rb
class Digital < ApplicationRecord
end

app/models/dog.rb
class Dog < ApplicationRecord
end

app/models/oneclick.rb
class Oneclick < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/payment_method.rb
class PaymentMethod < ApplicationRecord
  belongs_to :order
  belongs_to :payable
end

app/models/paypal.rb
class Paypal < ApplicationRecord
end

app/models/physical.rb
class Physical < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  has_many_attached :images
end

app/models/profile.rb
class Profile < ApplicationRecord
  has_one_attached :avatar
end

app/models/stripe.rb
class Stripe < ApplicationRecord
end

app/models/transbank.rb
class Transbank < ApplicationRecord
  belongs_to :method
end

app/models/webpay.rb
class Webpay < ApplicationRecord
end

app/controllers/payment_methods_controller.rb
class PaymentMethodsController < ApplicationController
  before_action :set_payment_method, only: %i[ show edit update destroy ]

  # GET /payment_methods or /payment_methods.json
  def index
    @payment_methods = PaymentMethod.all
  end

  # GET /payment_methods/1 or /payment_methods/1.json
  def show
  end

  # GET /payment_methods/new
  def new
    @payment_method = PaymentMethod.new
  end

  # GET /payment_methods/1/edit
  def edit
  end

  # POST /payment_methods or /payment_methods.json
  def create
    @payment_method = PaymentMethod.new(payment_method_params)

    respond_to do |format|
      if @payment_method.save
        format.html { redirect_to payment_method_url(@payment_method), notice: "Payment method was successfully created." }
        format.json { render :show, status: :created, location: @payment_method }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @payment_method.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payment_methods/1 or /payment_methods/1.json
  def update
    respond_to do |format|
      if @payment_method.update(payment_method_params)
        format.html { redirect_to payment_method_url(@payment_method), notice: "Payment method was successfully updated." }
        format.json { render :show, status: :ok, location: @payment_method }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @payment_method.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payment_methods/1 or /payment_methods/1.json
  def destroy
    @payment_method.destroy

    respond_to do |format|
      format.html { redirect_to payment_methods_url, notice: "Payment method was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment_method
      @payment_method = PaymentMethod.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def payment_method_params
      params.require(:payment_method).permit(:order_id, :payable_id)
    end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/payment_methods_helper.rb
module PaymentMethodsHelper
end

app/helpers/paypals_helper.rb
module PaypalsHelper
end

app/views/payment_methods/_form.html.erb
<%= form_with(model: payment_method, local: true) do |form| %>
  <% if payment_method.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(payment_method.errors.count, "error") %> prohibited this payment_method from being saved:</h2>

      <ul>
      <% payment_method.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :order_id %>
    <%= form.text_field :order_id %>
  </div>

  <div class="field">
    <%= form.label :payable_id %>
    <%= form.text_field :payable_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/payment_methods/edit.html.erb
<h1>Editing Payment Method</h1>

<%= render 'form', payment_method: @payment_method %>

<%= link_to 'Show', @payment_method %> |
<%= link_to 'Back', payment_methods_path %>

app/views/payment_methods/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Payment Methods</h1>

<table>
  <thead>
    <tr>
      <th>Order</th>
      <th>Payable</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @payment_methods.each do |payment_method| %>
      <tr>
        <td><%= payment_method.order %></td>
        <td><%= payment_method.payable %></td>
        <td><%= link_to 'Show', payment_method %></td>
        <td><%= link_to 'Edit', edit_payment_method_path(payment_method) %></td>
        <td><%= link_to 'Destroy', payment_method, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Payment Method', new_payment_method_path %>

app/views/payment_methods/new.html.erb
<h1>New Payment Method</h1>

<%= render 'form', payment_method: @payment_method %>

<%= link_to 'Back', payment_methods_path %>

app/views/payment_methods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Order:</strong>
  <%= @payment_method.order %>
</p>

<p>
  <strong>Payable:</strong>
  <%= @payment_method.payable %>
</p>

<%= link_to 'Edit', edit_payment_method_path(@payment_method) %> |
<%= link_to 'Back', payment_methods_path %>