config/routes.rb
Rails.application.routes.draw do
  resources :capybaras
  resources :dogs
  resources :cats
  resources :animals
  resources :transbanks
  resources :payment_methods
  resources :stripes
  resources :paypals
  resources :oneclicks
  resources :webpays
  resources :creditcards
  resources :orders
  resources :physicals
  resources :digitals
  resources :products
  resources :profiles
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/animal.rb
class Animal < ApplicationRecord
  belongs_to :specie
end

app/models/capybara.rb
class Capybara < ApplicationRecord
end

app/models/cat.rb
class Cat < ApplicationRecord
end

app/models/creditcard.rb
class Creditcard < ApplicationRecord
end

app/models/digital.rb
class Digital < ApplicationRecord
end

app/models/dog.rb
class Dog < ApplicationRecord
end

app/models/oneclick.rb
class Oneclick < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/payment_method.rb
class PaymentMethod < ApplicationRecord
  belongs_to :order
  belongs_to :payable
end

app/models/paypal.rb
class Paypal < ApplicationRecord
end

app/models/physical.rb
class Physical < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  has_many_attached :images
end

app/models/profile.rb
class Profile < ApplicationRecord
  has_one_attached :avatar
end

app/models/stripe.rb
class Stripe < ApplicationRecord
end

app/models/transbank.rb
class Transbank < ApplicationRecord
  belongs_to :method
end

app/models/webpay.rb
class Webpay < ApplicationRecord
end

app/controllers/oneclicks_controller.rb
class OneclicksController < ApplicationController
  before_action :set_oneclick, only: %i[ show edit update destroy ]

  # GET /oneclicks or /oneclicks.json
  def index
    @oneclicks = Oneclick.all
  end

  # GET /oneclicks/1 or /oneclicks/1.json
  def show
  end

  # GET /oneclicks/new
  def new
    @oneclick = Oneclick.new
  end

  # GET /oneclicks/1/edit
  def edit
  end

  # POST /oneclicks or /oneclicks.json
  def create
    @oneclick = Oneclick.new(oneclick_params)

    respond_to do |format|
      if @oneclick.save
        format.html { redirect_to oneclick_url(@oneclick), notice: "Oneclick was successfully created." }
        format.json { render :show, status: :created, location: @oneclick }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @oneclick.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /oneclicks/1 or /oneclicks/1.json
  def update
    respond_to do |format|
      if @oneclick.update(oneclick_params)
        format.html { redirect_to oneclick_url(@oneclick), notice: "Oneclick was successfully updated." }
        format.json { render :show, status: :ok, location: @oneclick }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @oneclick.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /oneclicks/1 or /oneclicks/1.json
  def destroy
    @oneclick.destroy

    respond_to do |format|
      format.html { redirect_to oneclicks_url, notice: "Oneclick was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_oneclick
      @oneclick = Oneclick.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def oneclick_params
      params.require(:oneclick).permit(:name)
    end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/oneclicks_helper.rb
module OneclicksHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/paypals_helper.rb
module PaypalsHelper
end

app/views/oneclicks/_form.html.erb
<%= form_with(model: oneclick, local: true) do |form| %>
  <% if oneclick.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(oneclick.errors.count, "error") %> prohibited this oneclick from being saved:</h2>

      <ul>
      <% oneclick.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/oneclicks/edit.html.erb
<h1>Editing Oneclick</h1>

<%= render 'form', oneclick: @oneclick %>

<%= link_to 'Show', @oneclick %> |
<%= link_to 'Back', oneclicks_path %>

app/views/oneclicks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Oneclicks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @oneclicks.each do |oneclick| %>
      <tr>
        <td><%= oneclick.name %></td>
        <td><%= link_to 'Show', oneclick %></td>
        <td><%= link_to 'Edit', edit_oneclick_path(oneclick) %></td>
        <td><%= link_to 'Destroy', oneclick, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Oneclick', new_oneclick_path %>

app/views/oneclicks/new.html.erb
<h1>New Oneclick</h1>

<%= render 'form', oneclick: @oneclick %>

<%= link_to 'Back', oneclicks_path %>

app/views/oneclicks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @oneclick.name %>
</p>

<%= link_to 'Edit', edit_oneclick_path(@oneclick) %> |
<%= link_to 'Back', oneclicks_path %>