config/routes.rb
Rails.application.routes.draw do
  resources :capybaras
  resources :dogs
  resources :cats
  resources :animals
  resources :transbanks
  resources :payment_methods
  resources :stripes
  resources :paypals
  resources :oneclicks
  resources :webpays
  resources :creditcards
  resources :orders
  resources :physicals
  resources :digitals
  resources :products
  resources :profiles
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/animal.rb
class Animal < ApplicationRecord
  belongs_to :specie
end

app/models/capybara.rb
class Capybara < ApplicationRecord
end

app/models/cat.rb
class Cat < ApplicationRecord
end

app/models/creditcard.rb
class Creditcard < ApplicationRecord
end

app/models/digital.rb
class Digital < ApplicationRecord
end

app/models/dog.rb
class Dog < ApplicationRecord
end

app/models/oneclick.rb
class Oneclick < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/payment_method.rb
class PaymentMethod < ApplicationRecord
  belongs_to :order
  belongs_to :payable
end

app/models/paypal.rb
class Paypal < ApplicationRecord
end

app/models/physical.rb
class Physical < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  has_many_attached :images
end

app/models/profile.rb
class Profile < ApplicationRecord
  has_one_attached :avatar
end

app/models/stripe.rb
class Stripe < ApplicationRecord
end

app/models/transbank.rb
class Transbank < ApplicationRecord
  belongs_to :method
end

app/models/webpay.rb
class Webpay < ApplicationRecord
end

app/controllers/webpays_controller.rb
class WebpaysController < ApplicationController
  before_action :set_webpay, only: %i[ show edit update destroy ]

  # GET /webpays or /webpays.json
  def index
    @webpays = Webpay.all
  end

  # GET /webpays/1 or /webpays/1.json
  def show
  end

  # GET /webpays/new
  def new
    @webpay = Webpay.new
  end

  # GET /webpays/1/edit
  def edit
  end

  # POST /webpays or /webpays.json
  def create
    @webpay = Webpay.new(webpay_params)

    respond_to do |format|
      if @webpay.save
        format.html { redirect_to webpay_url(@webpay), notice: "Webpay was successfully created." }
        format.json { render :show, status: :created, location: @webpay }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @webpay.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /webpays/1 or /webpays/1.json
  def update
    respond_to do |format|
      if @webpay.update(webpay_params)
        format.html { redirect_to webpay_url(@webpay), notice: "Webpay was successfully updated." }
        format.json { render :show, status: :ok, location: @webpay }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @webpay.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /webpays/1 or /webpays/1.json
  def destroy
    @webpay.destroy

    respond_to do |format|
      format.html { redirect_to webpays_url, notice: "Webpay was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_webpay
      @webpay = Webpay.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def webpay_params
      params.require(:webpay).permit(:name)
    end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/paypals_helper.rb
module PaypalsHelper
end

app/helpers/webpays_helper.rb
module WebpaysHelper
end

app/views/webpays/_form.html.erb
<%= form_with(model: webpay, local: true) do |form| %>
  <% if webpay.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(webpay.errors.count, "error") %> prohibited this webpay from being saved:</h2>

      <ul>
      <% webpay.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/webpays/edit.html.erb
<h1>Editing Webpay</h1>

<%= render 'form', webpay: @webpay %>

<%= link_to 'Show', @webpay %> |
<%= link_to 'Back', webpays_path %>

app/views/webpays/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Webpays</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @webpays.each do |webpay| %>
      <tr>
        <td><%= webpay.name %></td>
        <td><%= link_to 'Show', webpay %></td>
        <td><%= link_to 'Edit', edit_webpay_path(webpay) %></td>
        <td><%= link_to 'Destroy', webpay, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Webpay', new_webpay_path %>

app/views/webpays/new.html.erb
<h1>New Webpay</h1>

<%= render 'form', webpay: @webpay %>

<%= link_to 'Back', webpays_path %>

app/views/webpays/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @webpay.name %>
</p>

<%= link_to 'Edit', edit_webpay_path(@webpay) %> |
<%= link_to 'Back', webpays_path %>