config/routes.rb
Rails.application.routes.draw do
  resources :capybaras
  resources :dogs
  resources :cats
  resources :animals
  resources :transbanks
  resources :payment_methods
  resources :stripes
  resources :paypals
  resources :oneclicks
  resources :webpays
  resources :creditcards
  resources :orders
  resources :physicals
  resources :digitals
  resources :products
  resources :profiles
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/animal.rb
class Animal < ApplicationRecord
  belongs_to :specie
end

app/models/capybara.rb
class Capybara < ApplicationRecord
end

app/models/cat.rb
class Cat < ApplicationRecord
end

app/models/creditcard.rb
class Creditcard < ApplicationRecord
end

app/models/digital.rb
class Digital < ApplicationRecord
end

app/models/dog.rb
class Dog < ApplicationRecord
end

app/models/oneclick.rb
class Oneclick < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/payment_method.rb
class PaymentMethod < ApplicationRecord
  belongs_to :order
  belongs_to :payable
end

app/models/paypal.rb
class Paypal < ApplicationRecord
end

app/models/physical.rb
class Physical < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  has_many_attached :images
end

app/models/profile.rb
class Profile < ApplicationRecord
  has_one_attached :avatar
end

app/models/stripe.rb
class Stripe < ApplicationRecord
end

app/models/transbank.rb
class Transbank < ApplicationRecord
  belongs_to :method
end

app/models/webpay.rb
class Webpay < ApplicationRecord
end

app/controllers/stripes_controller.rb
class StripesController < ApplicationController
  before_action :set_stripe, only: %i[ show edit update destroy ]

  # GET /stripes or /stripes.json
  def index
    @stripes = Stripe.all
  end

  # GET /stripes/1 or /stripes/1.json
  def show
  end

  # GET /stripes/new
  def new
    @stripe = Stripe.new
  end

  # GET /stripes/1/edit
  def edit
  end

  # POST /stripes or /stripes.json
  def create
    @stripe = Stripe.new(stripe_params)

    respond_to do |format|
      if @stripe.save
        format.html { redirect_to stripe_url(@stripe), notice: "Stripe was successfully created." }
        format.json { render :show, status: :created, location: @stripe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @stripe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stripes/1 or /stripes/1.json
  def update
    respond_to do |format|
      if @stripe.update(stripe_params)
        format.html { redirect_to stripe_url(@stripe), notice: "Stripe was successfully updated." }
        format.json { render :show, status: :ok, location: @stripe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @stripe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stripes/1 or /stripes/1.json
  def destroy
    @stripe.destroy

    respond_to do |format|
      format.html { redirect_to stripes_url, notice: "Stripe was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stripe
      @stripe = Stripe.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def stripe_params
      params.fetch(:stripe, {})
    end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/paypals_helper.rb
module PaypalsHelper
end

app/helpers/stripes_helper.rb
module StripesHelper
end

app/views/stripes/_form.html.erb
<%= form_with(model: stripe, local: true) do |form| %>
  <% if stripe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(stripe.errors.count, "error") %> prohibited this stripe from being saved:</h2>

      <ul>
      <% stripe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stripes/edit.html.erb
<h1>Editing Stripe</h1>

<%= render 'form', stripe: @stripe %>

<%= link_to 'Show', @stripe %> |
<%= link_to 'Back', stripes_path %>

app/views/stripes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stripes</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stripes.each do |stripe| %>
      <tr>
        <td><%= link_to 'Show', stripe %></td>
        <td><%= link_to 'Edit', edit_stripe_path(stripe) %></td>
        <td><%= link_to 'Destroy', stripe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stripe', new_stripe_path %>

app/views/stripes/new.html.erb
<h1>New Stripe</h1>

<%= render 'form', stripe: @stripe %>

<%= link_to 'Back', stripes_path %>

app/views/stripes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_stripe_path(@stripe) %> |
<%= link_to 'Back', stripes_path %>